# Generated by Django 3.0.4 on 2020-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_nursery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nursery_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
