# Generated by Django 3.0.4 on 2020-06-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='example',
        ),
    ]
