# Generated by Django 3.0.4 on 2020-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0006_nursery'),
        ('shop', '0003_remove_orders_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='example',
            field=models.ManyToManyField(to='nursery.Nursery'),
        ),
    ]
