# Generated by Django 3.0.4 on 2020-06-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='example',
            new_name='nurseries',
        ),
    ]
