# Generated by Django 3.0.4 on 2020-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_auto_20200608_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=30)),
                ('plantPrice', models.IntegerField()),
                ('plantImage', models.ImageField(default='', upload_to='nursery/images')),
                ('plantDesc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
