# Generated by Django 3.0.4 on 2020-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_auto_20200608_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantNursery',
            field=models.CharField(default='', max_length=50),
        ),
    ]
