# Generated by Django 3.0.4 on 2020-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_plant_plantnursery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantNursery',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
